version: "3.3"
services:
  
  db: 
    image: mysql
    container_name: dbapp
    hostname: dbapp
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/sql/:/root/
    ports:
      - 127.0.0.1:3316:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  web:
    build: ./php/
    container_name: webapp
    hostname: webapp
    restart: always
    volumes:
      - ./php/src/lumen/:/var/www/html
    ports:
      - "8081:80"
    links:
      - db
    depends_on:
      - db